sudo: required

language: go
go:
  - 1.7
  
install:
  - mkdir -p $GOPATH/bin
  - curl https://glide.sh/get | sh

before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.3/elasticsearch-2.4.3.deb && sudo dpkg -i --force-confnew elasticsearch-2.4.3.deb && sudo service elasticsearch restart  

services: 
  - elasticsearch

before_script:
    - sleep 10

env: 
  - TEST_ELASTIC_BACKEND=true


