sudo: required

language: go
go:
  - 1.7
  
install:
  - mkdir -p $GOPATH/bin
  - curl https://glide.sh/get | sh
services: 
  - elasticsearch

before_script:
  - ./backend/elastic/wait.sh

env: 
  - TEST_ELASTIC_BACKEND=true


