sudo: required

language: go
go:
  - 1.7
  
install:
  - mkdir -p $GOPATH/bin
  - curl https://glide.sh/get | sh
services: 
  - elasticsearch

before_script:
  - until curl 127.0.0.1:9200/_cluster/health?pretty 2>&1 | grep status | egrep "(green|yellow)"; do
            printf '.'
            sleep 1
        done

env: 
  - TEST_ELASTIC_BACKEND=true


